name: CI Matrix

on: workflow_dispatch

jobs:
  matrix-build:
    strategy:
      matrix:
        version:
          [
            { docker: "v11.0", android: "34" },
            { docker: "6.0", android: "31" },
            { docker: "4", android: "30" },
            { docker: "8", android: "32" },
          ]
        ruby: ["2.7.4", "3.0.0"]
    name: Buid and push Docker image to GitHub Container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build Meta
        run: echo "::set-output name=dtag::ghcr.io/barelyhuman/docker-android:android-${{matrix.version.android}}-ruby-${{matrix.ruby}}"
        id: meta

      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          REGISTRY: ghcr.io
          OWNER: barelyhuman
          IMAGE_NAME: ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.dtag }}
          build-args: |
            BASE_VERSION=${{matrix.version.docker}}
            ENVIRONMENT=production
